baseurl = "https://alimy.github.io"
title = "北野"
author = "Michael Li"
copyright = "&copy;2018, Alimy; all rights reserved."
canonifyurls = true
paginate = 9
theme = "uno"

[params]
    name = "Alimy"
    logo = "/images/logo.jpg"
    cover = "/images/cover.jpg"
    description = "那年江湖，遇见你"
    cv = "/pages/cv"
    github = "alimy"
    twitter = "bitriory"
    disqus = "alimy"
